<?php
return[
    'user'=>[
        'status'=>[
            'pending'=>'pending_user',
            'adminApproved'=>'admin_approved_user',
            'superAdminApproved'=>'superAdmin_approved_user',
            'expired'=>'expired_user',
        ]
    ]
];
